// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","layout":false,"id":"1"},"2":{"path":"/","redirect":"/home","parentId":"1","id":"2"},"3":{"name":"首页","path":"/home","parentId":"1","id":"3"},"4":{"name":"达人库","path":"/creatorLibary","parentId":"1","id":"4"},"@@/global-layout":{"id":"@@/global-layout","path":"/","parentId":"ant-design-pro-layout","isLayout":true},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.jsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.jsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__CreatorLibary__index" */'@/pages/CreatorLibary/index.jsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/xwj/creatorVerve/src/layouts/index.jsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/xwj/creatorVerve/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
